In [4]:
%load_ext autoreload
%autoreload 2
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "-1"
import numpy as np
from matplotlib import pyplot as plt
import torch
from sparse_causal_model_learner_rl.sacred_gin_tune.sacred_wrapper import load_config_files
from sparse_causal_model_learner_rl.learners.rl_learner import CausalModelLearnerRL
from sparse_causal_model_learner_rl.config import Config
from tqdm.auto import tqdm
from torch import nn
import gin

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [5]:
gin.enter_interactive_mode()
load_config_files(['../keychest/config/5x5_1f1c1k.gin','../sparse_causal_model_learner_rl/configs/rec_nonlin_gnn.gin'])

['5x5_1f1c1k', 'rec_nonlin_gnn']

In [7]:
learner = CausalModelLearnerRL(Config())

Make environment KeyChest-v0 None {}


In [8]:
learner.create_trainables()

In [10]:
m = learner.model

In [11]:
m

ManyNetworkModel(
  (model_fout_0000): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0001): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0002): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0003): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0004): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02):

In [13]:
list(m.sparsify_me())

[('fc01.weight',
  tensor([0.1946, 0.1920, 0.2016, 0.2035, 0.2034, 0.2028, 0.1945, 0.1995, 0.1996,
          0.2000, 0.2038, 0.1948, 0.2034, 0.1993, 0.2026, 0.1978, 0.2016, 0.2039,
          0.2037, 0.1979, 0.2037, 0.2024, 0.2027, 0.2030],
         grad_fn=<MaxBackward0>)),
 ('fc01.weight',
  tensor([0.2019, 0.1909, 0.1990, 0.2007, 0.1989, 0.1936, 0.1923, 0.2035, 0.2024,
          0.2039, 0.1988, 0.2003, 0.1982, 0.2009, 0.1998, 0.1980, 0.1990, 0.1935,
          0.1961, 0.1977, 0.2036, 0.2010, 0.2027, 0.2029],
         grad_fn=<MaxBackward0>)),
 ('fc01.weight',
  tensor([0.2015, 0.2035, 0.2033, 0.1960, 0.2004, 0.2029, 0.2030, 0.1994, 0.2029,
          0.2039, 0.2027, 0.2001, 0.2038, 0.2012, 0.2000, 0.2025, 0.1991, 0.2013,
          0.1941, 0.2032, 0.1852, 0.2007, 0.2019, 0.2029],
         grad_fn=<MaxBackward0>)),
 ('fc01.weight',
  tensor([0.1988, 0.1906, 0.1943, 0.2013, 0.1995, 0.1973, 0.2005, 0.2036, 0.2025,
          0.1950, 0.2027, 0.2006, 0.1950, 0.2011, 0.1976, 0.2019, 0.2000, 0.

In [15]:
m.Mf.shape

(20, 20)

In [16]:
m.Ma.shape

(20, 4)

In [17]:
m.Ma

array([[0.20374401, 0.20238274, 0.20268819, 0.20299974],
       [0.20363376, 0.20098513, 0.20267183, 0.2029393 ],
       [0.18517931, 0.20074064, 0.2019374 , 0.20293395],
       [0.20101768, 0.20199856, 0.20286343, 0.19994685],
       [0.2004152 , 0.20263994, 0.20380232, 0.20250429],
       [0.20095327, 0.19639811, 0.20181361, 0.19811441],
       [0.20262057, 0.20280191, 0.19613686, 0.20362735],
       [0.18963528, 0.20230703, 0.20345731, 0.1992001 ],
       [0.202961  , 0.19969714, 0.20268056, 0.20291105],
       [0.20284882, 0.20258026, 0.20113674, 0.20035455],
       [0.20351386, 0.19891545, 0.1956115 , 0.20325628],
       [0.20282619, 0.20220704, 0.20161347, 0.20184776],
       [0.1938379 , 0.1930647 , 0.20370302, 0.20371032],
       [0.19911486, 0.19968696, 0.1881845 , 0.20216656],
       [0.20350963, 0.20058645, 0.2004635 , 0.202897  ],
       [0.20282167, 0.195824  , 0.20364548, 0.19712442],
       [0.20014518, 0.20073031, 0.19966672, 0.20014846],
       [0.19790213, 0.20069559,

In [18]:
m.state_dict()

OrderedDict([('model_fout_0000.fc01.weight',
              tensor([[-0.0496, -0.0913, -0.0976,  ..., -0.0368, -0.0329, -0.0743],
                      [ 0.0458,  0.0933,  0.1643,  ...,  0.0681,  0.1633, -0.0715],
                      [ 0.1830,  0.0288, -0.1871,  ...,  0.0486,  0.1231,  0.0606],
                      ...,
                      [ 0.0216, -0.0049,  0.1363,  ..., -0.0294, -0.0053,  0.1923],
                      [-0.1143,  0.1783, -0.1452,  ...,  0.1019,  0.0258, -0.1508],
                      [-0.1127, -0.1060,  0.0920,  ..., -0.1388,  0.1565, -0.1066]])),
             ('model_fout_0000.fc01.bias',
              tensor([ 0.1639, -0.0160,  0.1672, -0.1070, -0.1075,  0.0260,  0.0867,  0.0746,
                       0.1734, -0.0403, -0.0109, -0.0203,  0.1886, -0.0347, -0.1833,  0.0372,
                       0.1139, -0.1670, -0.0685,  0.1852, -0.0015, -0.1119,  0.0197, -0.0283,
                      -0.0313,  0.1901,  0.1625,  0.1346, -0.1745,  0.0381, -0.1665, -0.0661,
  