In [1]:
%load_ext autoreload
%autoreload 2
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "-1"
import numpy as np
from matplotlib import pyplot as plt
import torch
from sparse_causal_model_learner_rl.sacred_gin_tune.sacred_wrapper import load_config_files
from sparse_causal_model_learner_rl.learners.rl_learner import CausalModelLearnerRL
from sparse_causal_model_learner_rl.config import Config
from tqdm.auto import tqdm
from torch import nn
import gin

In [2]:
gin.enter_interactive_mode()
load_config_files(['../keychest/config/5x5_1f1c1k.gin','../sparse_causal_model_learner_rl/configs/rec_nonlin_gnn.gin'])

['5x5_1f1c1k', 'rec_nonlin_gnn']

In [3]:
learner = CausalModelLearnerRL(Config())

Make environment KeyChest-v0 None {}


In [4]:
learner.create_trainables()

In [5]:
m = learner.model

In [6]:
m

ManyNetworkModel(
  (model_fout_0000): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0001): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0002): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0003): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02): Linear(in_features=50, out_features=25, bias=True)
    (fc03): Linear(in_features=25, out_features=1, bias=True)
  )
  (model_fout_0004): FCNet(
    (fc01): Linear(in_features=24, out_features=50, bias=True)
    (fc02):

In [7]:
list(m.sparsify_me())

[('model_fout_0000.fc01.weight',
  tensor([0.1980, 0.2034, 0.2020, 0.2027, 0.1991, 0.2021, 0.2015, 0.2041, 0.2037,
          0.2029, 0.2015, 0.2017, 0.1986, 0.2019, 0.2039, 0.2035, 0.2040, 0.2040,
          0.2005, 0.2012, 0.2009, 0.1960, 0.2015, 0.1989],
         grad_fn=<MaxBackward0>)),
 ('model_fout_0001.fc01.weight',
  tensor([0.2016, 0.2001, 0.1998, 0.2005, 0.1991, 0.2039, 0.1968, 0.2009, 0.2038,
          0.2034, 0.2034, 0.2040, 0.1944, 0.1966, 0.2001, 0.1970, 0.1976, 0.1979,
          0.2034, 0.2018, 0.1961, 0.2032, 0.2024, 0.2039],
         grad_fn=<MaxBackward0>)),
 ('model_fout_0002.fc01.weight',
  tensor([0.2039, 0.1978, 0.2027, 0.2007, 0.2034, 0.1978, 0.2012, 0.2003, 0.1978,
          0.2039, 0.2036, 0.2010, 0.1994, 0.2011, 0.2027, 0.2006, 0.2005, 0.1965,
          0.2031, 0.2034, 0.1961, 0.2011, 0.2021, 0.1995],
         grad_fn=<MaxBackward0>)),
 ('model_fout_0003.fc01.weight',
  tensor([0.1981, 0.2006, 0.2029, 0.2011, 0.2033, 0.2030, 0.2008, 0.2034, 0.2016,
          0.

In [8]:
m.Mf.shape

(20, 20)

In [9]:
m.Ma.shape

(20, 4)

In [10]:
m.Ma

array([[0.20093152, 0.19596863, 0.20152001, 0.1989375 ],
       [0.19605836, 0.20320064, 0.20237368, 0.20390992],
       [0.19613048, 0.20109636, 0.20209455, 0.19949228],
       [0.20061475, 0.20003101, 0.20342731, 0.19700834],
       [0.2013807 , 0.20187548, 0.20104432, 0.2008273 ],
       [0.20008767, 0.20312928, 0.19481087, 0.19413388],
       [0.19888446, 0.18635169, 0.20226133, 0.20065325],
       [0.20398045, 0.20232728, 0.20357758, 0.20211829],
       [0.2031641 , 0.20168814, 0.20282292, 0.20194733],
       [0.19838864, 0.20093097, 0.20285825, 0.2030819 ],
       [0.20227444, 0.20185778, 0.19964047, 0.20267406],
       [0.19855164, 0.20043346, 0.20290652, 0.20407026],
       [0.19985124, 0.18710133, 0.1986967 , 0.20388836],
       [0.20170207, 0.19402754, 0.20061481, 0.2025635 ],
       [0.20390241, 0.19959088, 0.20067045, 0.2039314 ],
       [0.20351616, 0.20324436, 0.20163181, 0.19870237],
       [0.20045444, 0.201029  , 0.202239  , 0.19065058],
       [0.20191118, 0.20383641,

In [11]:
m.state_dict()

OrderedDict([('model_fout_0000.fc01.weight',
              tensor([[ 0.0093, -0.0235,  0.1191,  ..., -0.0899, -0.2015,  0.0911],
                      [-0.0019, -0.1589,  0.0534,  ...,  0.1807, -0.0292,  0.1845],
                      [-0.1113,  0.1767,  0.0305,  ..., -0.1625, -0.1347, -0.0797],
                      ...,
                      [ 0.0691,  0.1865, -0.1030,  ..., -0.0053, -0.0914,  0.0967],
                      [ 0.0552,  0.1954, -0.0764,  ..., -0.1370, -0.1508,  0.0713],
                      [ 0.0076,  0.1215, -0.0593,  ...,  0.1621, -0.1721, -0.0945]])),
             ('model_fout_0000.fc01.bias',
              tensor([-0.0251, -0.1590, -0.1751, -0.1637,  0.1167, -0.0407, -0.0558, -0.1989,
                       0.0866,  0.0576, -0.1545,  0.0247, -0.1693,  0.0319, -0.0543, -0.0856,
                      -0.0027,  0.1939,  0.1970,  0.1877,  0.1375,  0.0678, -0.0692, -0.1844,
                      -0.1656,  0.1383, -0.1444,  0.0560, -0.1044, -0.0875,  0.1254,  0.1676,
  